#install.packages("UpSetR")
library(UpSetR)

# Dataset
input <- c(
  S.Pneumoniae = 1462,
  S.Suis = 1279,
  S.Agalactiae = 1556,
  S.Equi_sb_equi = 1786,
  S.Iniae = 1561,
  S.Uberis = 1423,
  "S.Suis&S.Pneumoniae" = 915,
  "S.Equi_sb_equi&S.Pneumoniae" = 820,
  "S.Agalactiae&S.Equi_sb_equi" =1075,
  "S.Iniae&S.Agalactiae" = 1045,
  "S.Equi_sb_equi&S.Suis" = 902,
  "S.Iniae&S.Suis" = 881,
  "S.Iniae&S.Pneumoniae" = 833,
  "S.Uberis&S.Equi_sb_equi" = 828,
  "S.Iniae&S.Equi_sb_equi" = 893,
  "S.Uberis&S.Agalactiae" = 909,
  "S.Uberis&S.Pneumoniae" = 846,
  "S.Uberis&S.Iniae" = 799,
  "S.Pneumoniae&S.Agalactiae" = 871,
  "S.Agalactiae&S.Suis" = 911,
  "S.Uberis&S.Suis" = 890,
  "S.Iniae&S.Equi_sb_equi&S.Suis" = 844,
  "S.Uberis&S.Equi_sb_equi&S.Suis" = 903,
  "S.Iniae&S.Equi_sb_equi&S.Uberis" = 952,
  "S.Uberis&S.Equi_sb_equi&S.Agalactiae" = 811,
  "S.Iniae&S.Equi_sb_equi&S.Agalactiae" = 961,
  "S.Iniae&S.Uberis&S.Agalactiae" = 901,
  "S.Equi_sb_equi&S.Uberis&S.Pneumoniae" = 805,
  "S.Iniae&S.Uberis&S.Pneumoniae" = 786,
  "S.Equi_sb_equi&S.Pneumoniae&S.Suis" = 809,
  "S.Pneumoniae&S.Iniae&S.Agalactiae" = 821,
  "S.Uberis&S.Pneumoniae&S.Agalactiae" = 817,
  "S.Equi_sb_equi&S.Pneumoniae&S.Agalactiae" = 799,
  "S.Pneumoniae&S.Suis&S.Agalactiae" = 855,
  "S.Suis&S.Agalactiae&S.Iniae" = 871,
  "S.Equi_sb_equi&S.Agalactiae&S.Suis" = 886,
  "S.Iniae&S.Equi_sb_equi&S.Pneumoniae" = 804,
  "S.Iniae&S.Pneumoniae&S.Suis" = 810,
  "S.Uberis&S.Agalactiae&S.Suis" = 831,
  "S.Uberis&S.Pneumoniae&S.Suis" = 793,
  "S.Uberis&S.Iniae&S.Suis" = 790,
  "S.Pneumoniae&S.Uberis&S.Iniae&S.Agalactiae" = 777,
  "S.Suis&S.Iniae&S.Equi_sb_equi&S.Pneumoniae" = 768,
  "S.Uberis&S.Equi_sb_equi&S.Pneumoniae&S.Suis" = 784,
  "S.Iniae&S.Uberis&S.Equi_sb_equi&S.Agalactiae" = 769,
  "S.Equi_sb_equi&S.Pneumoniae&S.Agalactiae&S.Iniae" = 771,
  "S.Pneumoniae&S.Equi_sb_equi&S.Suis&S.Agalactiae" = 772,
  "S.Uberis&S.Pneumoniae&S.Equi_sb_equi&S.Agalactiae" = 787,
  "S.Uberis&S.Iniae&S.Suis&S.Agalactiae" = 788,
  "S.Uberis&S.Equi_sb_equi&S.Suis&S.Agalactiae" = 783,
  "S.Agalactiae&S.Suis&S.Iniae&S.Equi_sb_equi" = 780,
  "S.Pneumoniae&S.Iniae&S.Suis&S.Agalactiae" = 774,
  "S.Pneumoniae&S.Uberis&S.Iniae&S.Suis" = 767,
  "S.Pneumoniae&S.Equi_sb_equi&S.Iniae&S.Uberis" = 778,
  "S.Suis&S.Uberis&S.Iniae&S.Equi_sb_equi" = 771,
  "S.Suis&S.Uberis&S.Iniae&S.Equi_sb_equi&S.Agalactiae" = 769,
  "S.Suis&S.Pneumoniae&S.Iniae&S.Uberis&S.Equi_sb_equi" = 738,
  "S.Pneumoniae&S.Iniae&S.Uberis&S.Equi_sb_equi&S.Agalactiae" = 751,
  "S.Iniae&S.Pneumoniae&S.Suis&S.Equi_sb_equi&S.Agalactiae" = 733,
  "S.Uberis&S.Pneumoniae&S.Suis&S.Equi_sb_equi&S.Agalactiae" = 744,
  "S.Pneumoniae&S.Iniae&S.Uberis&S.Suis&S.Agalactiae" = 740,
  "S.Pneumoniae&S.Iniae&S.Uberis&S.Suis&S.Equi_sb_equi&S.Agalactiae" = 716
)


# Plot
upset(fromExpression(input), 
      nintersects = 70, 
      nsets = 6, 
      order.by = "freq", 
      decreasing = T, 
      mb.ratio = c(0.6, 0.4),
      number.angles = 0, 
      text.scale = c(1.1, 1.1, 1.1, 1.1, 1.1, 0.8), 
      point.size = 2.8, 
      line.size = 1,
      mainbar.y.label = "Essentialome", sets.x.label = "total number of gene intersections",
)

#make bar plot